version: "3.9"
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "9080:8080"
    environment:
      BASE_URL: /swagger
      API_URL: http://localhost:8080/test/v1.0/swagger
    depends_on:
      - test

  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: services
      POSTGRES_MAX_CONNECTIONS: 300
      TZ: UTC
      PGTZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # THIS WAS MISSING
      test: ["CMD-SHELL", "pg_isready -U dummy -d services"]
      interval: 10s
      timeout: 5s
      retries: 10

  test:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgresql://dummy:dummy@postgres:5432/services"
    depends_on:
      postgres:
        condition: service_healthy  # Requires healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
